### ISSUE TITLE
Cannot read property 'stage' of undefined

### ISSUE THREAD

**Issue by nbransby** [svdgraaf/serverless-plugin-stage-variables#9] opened 2017-04-03 02:47 UTC
Im getting this after updating to latest version of serverless - 1.10

**Comment by kohtomo** [comment] 2017-04-04 00:34
I am troubled with the same error.
It seems to be caused by the following code.

src/index.html line:27
`var stage = this._serverless.service.defaults.stage;`

defaults is undefined.

**Comment by alexef** [comment] 2017-04-18 09:13
Is there a way to get the fix in a release?

**Comment by mikefrancis** [comment] 2017-05-08 13:51
Getting the same problem, would be great if the fix could get released.

**Comment by mikefrancis** [comment] 2017-05-15 14:56
Any news @svdgraaf? I'm having to ask colleagues to implement the fix in the commit above each time we onboard them to a project.

**Comment by nbransby** [comment] 2017-05-15 15:00
Has @idandush submitted a PR with that fix? In the meantime you can point to his fork in your package.json

**Comment by svdgraaf** [comment] 2017-05-23 11:49
Crap! I complete lost track of this repo! I'm reading back right now, sorry!

**Comment by svdgraaf** [comment] 2017-05-23 12:02
I was waaaaaay behind on github notifications, so only just found all the issues. The mentioned PR is merged, and I just releases a new revision v1.7.7 which includes this change/fix.

Sorry for the delay, and thanks again! 👏

**Closed as completed by svdgraaf** 2017-05-23 12:02 UTC
